### ISSUE TITLE
Add support for OpenEXR

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/scape#18]
I think it might be useful to add support for OpenEXR in importing/exporting images.
According to their [website](http://www.openexr.com/) they have:
> Support for 16-bit floating-point, 32-bit floating-point, and 32-bit integer pixels.

If I understood it right, OGRE itself even has OpenEXR support by the EXRCodec plugin, which, however seems to lack some features:
https://github.com/OGRECave/ogre/blob/cd252a4e151fb5aa8550db016963a098c29ee9f0/PlugIns/EXRCodec/src/OgreEXRCodec.cpp#L60-L64

**Comment by paroj** [comment]
Codec_STBI can also write HDR files (32bit float RGBA) and Codec_FreeImage can even directly write EXR files.
