### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/scape#24]
Can we require the usage of the C++11 standard for this project?
It looks to me like OGRE requires this itself.
https://github.com/OGRECave/ogre/blob/f4709042cf7722757d86fa830fedea0985017d53/CMakeLists.txt#L19-L21

**Comment by paroj** [comment]
yup.. Ogre 1.11 requires C++11 and this requires Ogre 1.11 :wink:
