### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/scape#31]
Maybe this program could need a version scheme.
The original program stopped at 0.1.1.
Someone wrote 15.02 in the title which seems random to me.
But I don't know how to do this and if this is really necessary.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I think the original author intended to use [semantic versioning](https://semver.org/).
Even if not, I would find this scheme useful.
I think the next version could be 0.2.0 because I think that the current state is still a development version but now has nearly the same functions as the original version.

**Comment by paroj** [comment]
I think semver is mostly useful for libraries where you have an public API. For UI driven projects I would prefer the release date as the version (e.g. 19.08). But thats just my personal opinion. You can do as you like - as long as the scheme is monotonically increasing

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
Indeed, it makes more sense to use the release date for the editor.
Of course, semver would only make sense for the scape engine part, but it doesn't need a version (yet).
So I think it would be the best way to release both with the release date as version.
Thanks for the answer.👍
