### ISSUE TITLE
Refactor about-dialog text

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/scape#32]
Someone put a random text inside the about-dialog.
Someone could think about a nice text for this.
Maybe related to #31.

![screen](https://user-images.githubusercontent.com/34325939/50614152-2358dc00-0ee0-11e9-90f4-0c71bdd55ac1.png)

**Comment by paroj** [comment]
Just copy/ paste the first paragraph of the README

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
![about](https://user-images.githubusercontent.com/34325939/64077095-fc4fe580-cccc-11e9-8e98-aa79afd43faa.png)
