### ISSUE TITLE
Determine version number

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/scape#44]
To determine the version number I see two possible ways:
1. Set the version number with CMake in the [project() command](https://cmake.org/cmake/help/latest/command/project.html).
2. Use git to use a tag name and a commit hash as version number.

One could then generate a file like ScapeVersion.h which defines the version number after being generated by CMake using the [configure_file() command](https://cmake.org/cmake/help/latest/command/configure_file.html).

The first way is easier to set up but the second way doesn't need as much maintenance but may be a bit more inaccurate.

I don't know which way could be better.

**Comment by paroj** [comment]
I prefer the first option as it does not rely on git being present (think of tarball downloads). It is also the one I use for ogre itself.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I used something very similar to the first one.
I manually defined the version because the project() command removes leading zeros in the version before CMake version 3.16.
