### ISSUE TITLE
Crashes on usage of GPU brushes

### ISSUE THREAD

**Issue by paroj** [OGRECave/scape#8]
* Noise GPU
* Directional noise GPU

the following work fine
* Noise CPU
* Soften GPU
* Eraser GPU

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I think this could be related to #6, because this was the same for me.
The shaders silently failed to compile (writing to log, of course), but the program still ran.
Then after using a brush it crashed.

**Comment by paroj** [comment]
indeed using *p40 fixed it for me as well
